# Generated by Django 4.1 on 2022-10-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=122)),
                ('time', models.IntegerField()),
                ('category', models.CharField(max_length=122)),
                ('count_id', models.IntegerField()),
                ('status', models.BooleanField(default='False')),
            ],
        ),
    ]
