# Generated by Django 4.1 on 2022-10-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_home', '0002_t_user_alter_todo_count_id_todo_use_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_user',
            name='email',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='t_user',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='t_user',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
